In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "Name": ["Ram", "Shyam", "Ram", "Sita", None,"Shyam","Shyam","Shyam","Ram"],
    "Age": [25, np.nan, 25, 30, 22,13,17,18,19],
    "City": ["Mumbai", "mumbai", "Mumbai", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi"]
}
print(data)
df = pd.DataFrame(data)
df

{'Name': ['Ram', 'Shyam', 'Ram', 'Sita', None, 'Shyam', 'Shyam', 'Shyam', 'Ram'], 'Age': [25, nan, 25, 30, 22, 13, 17, 18, 19], 'City': ['Mumbai', 'mumbai', 'Mumbai', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi']}

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

In [4]:
# First few rows
print(df.head())

# Data info
df.info()

# Summary statistics
df.describe()

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      float64
 2   City    9 non-null      object
dtypes: float64(1), object(2)
memory usage: 348.0+ bytes

            Age
count   8.00000
mean   21.12500
std     5.43632
min    13.00000
25%    17.75000
50%    20.50000
75%    25.00000
max    30.00000

In [5]:
# Check missing values
df.isnull()

# Count missing values
df.isnull().sum()

Name    1
Age     1
City    0
dtype: int64

In [6]:
# Drop rows with missing values
df_drop = df.dropna()
df_drop

    Name   Age    City
0    Ram  25.0  Mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

In [7]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])


df

    Name     Age    City
0    Ram  25.000  Mumbai
1  Shyam  21.125  mumbai
2    Ram  25.000  Mumbai
3   Sita  30.000   Delhi
4  Shyam  22.000   Delhi
5  Shyam  13.000   Delhi
6  Shyam  17.000   Delhi
7  Shyam  18.000   Delhi
8    Ram  19.000   Delhi

In [8]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, np.nan, 25, 30,20],
    "Salary": [20000, 25000, np.nan, 40000,20000],
    "City": ["Nashik", "Delhi", "Pune", "Akola","Mumbai"]
})

df

    Age   Salary    City
0  20.0  20000.0  Nashik
1   NaN  25000.0   Delhi
2  25.0      NaN    Pune
3  30.0  40000.0   Akola
4  20.0  20000.0  Mumbai

In [9]:
# Fill multiple columns with mean

df[["Age", "Salary"]] = df[["Age", "Salary"]].fillna(df[["Age", "Salary"]].mean())

df

     Age   Salary    City
0  20.00  20000.0  Nashik
1  23.75  25000.0   Delhi
2  25.00  26250.0    Pune
3  30.00  40000.0   Akola
4  20.00  20000.0  Mumbai

In [10]:
# Convert multiple columns to integer

df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)

df.dtypes
df

   Age  Salary    City
0   20   20000  Nashik
1   23   25000   Delhi
2   25   26250    Pune
3   30   40000   Akola
4   20   20000  Mumbai

In [11]:
# Increase values by 10%

df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)

df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0  Mumbai

In [12]:
df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0  Mumbai

In [13]:
# Replace specific values

df[["City"]] = df[["City"]].replace("Mumbai", "Pune")

df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0    Pune

In [14]:
df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0    Pune

In [15]:
df_encoded = pd.get_dummies(df, columns=["City"])
df_encoded

    Age   Salary  City_Akola  City_Delhi  City_Nashik  City_Pune
0  22.0  22000.0       False       False         True      False
1  25.3  27500.0       False        True        False      False
2  27.5  28875.0       False       False        False       True
3  33.0  44000.0        True       False        False      False
4  22.0  22000.0       False       False        False       True

In [16]:
df_no_dup = df.drop_duplicates()
df_no_dup

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0    Pune

In [17]:
# Convert all city names to lowercase
df["City"] = df["City"].str.upper()
df2=df.dropna()
#FEMALE female Female FeMale
df2

    Age   Salary    City
0  22.0  22000.0  NASHIK
1  25.3  27500.0   DELHI
2  27.5  28875.0    PUNE
3  33.0  44000.0   AKOLA
4  22.0  22000.0    PUNE

In [18]:
df2.dropna()
df2["Age"] = df2["Age"].astype(int)
df2

   Age   Salary    City
0   22  22000.0  NASHIK
1   25  27500.0   DELHI
2   27  28875.0    PUNE
3   33  44000.0   AKOLA
4   22  22000.0    PUNE

In [19]:
from google.colab import files

uploaded = files.upload()

Saving rainfall_weather_dataset.csv to rainfall_weather_dataset.csv

In [20]:
# Check uploaded file name
file_name = list(uploaded.keys())[0]
print("Uploaded file:", file_name)

Uploaded file: rainfall_weather_dataset.csv

In [21]:
import pandas as pd

# Load the uploaded file
df = pd.read_csv(file_name)

df.head()

         date  rainfall  temperature  humidity  wind_speed weather_condition
0  2022-01-01       0.0         22.7      52.0         7.3             Sunny
1  2022-01-02       0.0         19.7      46.4         7.3             Sunny
2  2022-01-03       3.7         23.7      74.8         8.8            Cloudy
3  2022-01-04       0.0         24.1      54.6        12.3             Sunny
4  2022-01-05       0.0         17.7      34.0        10.2             Sunny

In [22]:
df.head()

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1095 non-null   object
 1   rainfall           1095 non-null   float64
 2   temperature        1095 non-null   float64
 3   humidity           1095 non-null   float64
 4   wind_speed         1095 non-null   float64
 5   weather_condition  1095 non-null   object
dtypes: float64(4), object(2)
memory usage: 51.5+ KB

date                 0
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64

In [23]:
df["date"] = df["date"].astype(str).str.strip()
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1095 non-null   datetime64[ns]
 1   rainfall           1095 non-null   float64
 2   temperature        1095 non-null   float64
 3   humidity           1095 non-null   float64
 4   wind_speed         1095 non-null   float64
 5   weather_condition  1095 non-null   object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 51.5+ KB

In [24]:
import pandas as pd

# Numerical columns
num_cols = ["rainfall", "temperature", "humidity", "wind_speed"]

# Fill numerical missing values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Fill categorical missing values with mode
df["weather_condition"] = df["weather_condition"].fillna(df["weather_condition"].mode()[0])

# Check missing values
print(df.isnull().sum())

date                 0
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64

In [25]:
df["weather_condition"] = df["weather_condition"].str.lower()

df["weather_condition"].unique()

df.head()

        date  rainfall  temperature  humidity  wind_speed weather_condition
0 2022-01-01       0.0         22.7      52.0         7.3             sunny
1 2022-01-02       0.0         19.7      46.4         7.3             sunny
2 2022-01-03       3.7         23.7      74.8         8.8            cloudy
3 2022-01-04       0.0         24.1      54.6        12.3             sunny
4 2022-01-05       0.0         17.7      34.0        10.2             sunny

In [26]:
df.to_csv("cleaned_rainfall.csv", index=False)

# Download
files.download("cleaned_rainfall.csv")

In [27]:
import pandas as pd
from google.colab import files

# Convert to Excel
df.to_excel("cleaned_rainfall.xlsx", index=False)

# Download
files.download("cleaned_rainfall.xlsx")

In [28]:
import pandas as pd
import numpy as np

data = {
    "name": ["Amit", "Sara", "John", "Amit", None],
    "age": [20, 21, np.nan, 20, 19],
    "gender": ["Male", "female", "Male", "Male", "FEMALE"],
    "marks": [85, 90, 105, 85, -5],
    "attendance": [90, 85, 80, 90, None],
    "city": ["Mumbai", "Delhi", "mumbai", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df

   name   age  gender  marks  attendance    city
0  Amit  20.0    Male     85        90.0  Mumbai
1  Sara  21.0  female     90        85.0   Delhi
2  John   NaN    Male    105        80.0  mumbai
3  Amit  20.0    Male     85        90.0  Mumbai
4  None  19.0  FEMALE     -5         NaN    Pune

In [29]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   age         4 non-null      float64
 2   gender      5 non-null      object
 3   marks       5 non-null      int64
 4   attendance  4 non-null      float64
 5   city        5 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 372.0+ bytes

             age       marks  attendance
count   4.000000    5.000000    4.000000
mean   20.000000   72.000000   86.250000
std     0.816497   43.817805    4.787136
min    19.000000   -5.000000   80.000000
25%    19.750000   85.000000   83.750000
50%    20.000000   85.000000   87.500000
75%    20.250000   90.000000   90.000000
max    21.000000  105.000000   90.000000

In [30]:
df["age"].fillna(df["age"].mean(), inplace=True)
df["attendance"].fillna(df["attendance"].mean(), inplace=True)
df["name"].fillna("Unknown", inplace=True)

df

/tmp/ipykernel_3979/1440735091.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)
/tmp/ipykernel_3979/1440735091.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["attendance"].fillna(df["attendance"].mean(), inplace=True)
/tmp/ipykernel_3979/1440735091.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["name"].fillna("Unknown", inplace=True)

      name   age  gender  marks  attendance    city
0     Amit  20.0    Male     85       90.00  Mumbai
1     Sara  21.0  female     90       85.00   Delhi
2     John  20.0    Male    105       80.00  mumbai
3     Amit  20.0    Male     85       90.00  Mumbai
4  Unknown  19.0  FEMALE     -5       86.25    Pune

In [31]:
df["age"].fillna(df["age"].mean(), inplace=True)
df["attendance"].fillna(df["attendance"].mean(), inplace=True)
df["name"].fillna("Unknown", inplace=True)

df

/tmp/ipykernel_3979/1440735091.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)
/tmp/ipykernel_3979/1440735091.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["attendance"].fillna(df["attendance"].mean(), inplace=True)
/tmp/ipykernel_3979/1440735091.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["name"].fillna("Unknown", inplace=True)

      name   age  gender  marks  attendance    city
0     Amit  20.0    Male     85       90.00  Mumbai
1     Sara  21.0  female     90       85.00   Delhi
2     John  20.0    Male    105       80.00  mumbai
3     Amit  20.0    Male     85       90.00  Mumbai
4  Unknown  19.0  FEMALE     -5       86.25    Pune

In [32]:
df = df[(df["marks"] >= 0) & (df["marks"] <= 100)]

df

   name   age  gender  marks  attendance    city
0  Amit  20.0    Male     85        90.0  Mumbai
1  Sara  21.0  female     90        85.0   Delhi
3  Amit  20.0    Male     85        90.0  Mumbai